### ISSUE TITLE
Want to use oculus rift to control UR3

### ISSUE THREAD

**Issue by NAISGH** [devvaibhav455/UR5_VR_teleop#1]
I want to control the movement of UR3 through the oculus rift controller like you. In addition to modifying the configuration file, where do I need to modify the main program?

**Comment by devvaibhav455** [comment]
I think just changing the IP should be fine. If you are working on a real robot,I would suggest testing first on simulation. However, I don't know how to fetch the raw values from Oculus. But the idea is that the script needs to get 6-DOF goal pose from any source on the topic `/vive_gripper` as part of a `visualization_msgs/Marker` message

`self.ROBOT_IP = '127.0.0.1' if self.cfg['sim'] == 'true' else '10.75.15.194'`

I believe the URBasic library should also work with UR3 as it is written here [https://github.com/martinbjerge/ur-interface](https://github.com/martinbjerge/ur-interface)

All the best!

**Comment by devvaibhav455** [comment]
@NAISGH : Shall I close the issue because I don't see any further activity?

**Comment by NAISGH** [comment]
Thank you very much. I will consult you again if I encounter any new problems in the future.
